# Generated by Django 3.2.6 on 2021-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcohol_amount',
            field=models.CharField(blank=True, choices=[('알쓰', '1잔 ~ 4잔'), ('평민', '5잔 ~ 1.5병'), ('술의 요정', '1.5병 ~ 2.5병'), ('타노스', '2.5병 ~ 5병 이상')], max_length=32, null=True),
        ),
    ]
