# Generated by Django 3.2.6 on 2021-08-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_alcohol_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='alcohol_amount',
            field=models.CharField(blank=True, choices=[('소주 0병', '소주 0병'), ('소주 반병', '소주 반병'), ('소주 한병', '소주 한병'), ('소주 한병 반', '소주 한병 반'), ('소주 두병', '소주 두병'), ('소주 세병 이상', '소주 세병 이상')], max_length=32, null=True),
        ),
    ]
