# Generated by Django 3.2.6 on 2021-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcohol_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
