# Generated by Django 3.2.6 on 2021-08-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcohol_amount',
            field=models.FloatField(blank=True),
        ),
    ]
