# Generated by Django 3.2.6 on 2021-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210826_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alcohol_amount',
            field=models.FloatField(blank=True),
        ),
    ]
