# Generated by Django 3.2.6 on 2021-08-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='노래 제목')),
                ('photo', models.CharField(max_length=100, verbose_name='앨범 사진 이름')),
                ('singer', models.CharField(max_length=100, verbose_name='가수 이름')),
                ('file_name', models.CharField(max_length=100, verbose_name='음원 파일 이름')),
            ],
            options={
                'db_table': 'music',
            },
        ),
    ]
