# Generated by Django 3.2.6 on 2021-08-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '방명록'},
        ),
    ]
