# Generated by Django 3.2.6 on 2021-08-26 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(blank=True, db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='like_post', to='post.post')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likeposts',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='likepost',
            field=models.ManyToManyField(blank=True, related_name='like_post', through='post.LikePost', to=settings.AUTH_USER_MODEL),
        ),
    ]
