# Generated by Django 3.2.6 on 2021-08-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210826_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='is_like',
        ),
    ]
