# Generated by Django 3.2.6 on 2021-08-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(blank=True)),
                ('answer', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'mbti',
            },
        ),
        migrations.CreateModel(
            name='MbtiResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mbti', models.CharField(max_length=10, unique=True, verbose_name='mbti 유형')),
                ('comment', models.TextField(blank=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
            options={
                'db_table': 'mbti_result',
            },
        ),
    ]
